import { Product } from '../types/domain';

export const LOCAL_FISH_PRODUCTS: Product[] = [
    // --- MARIN CATEGORY ---
    {
        id: 'marin_lobster',
        name: "Fresh Atlantic Lobster",
        category: "marin",
        categoryId: "marin",
        pack: "500g - 1kg",
        price: 1899,
        imageUrl: "/images/marin_lobster.png",
        rating: 4.9,
        description: "Premium large lobster, perfect for gourmet dishes.",
        stock: 15,
        isAvailable: true
    },
    {
        id: 'marin_prawns',
        name: "Tiger Prawns (Jumbo)",
        category: "marin",
        categoryId: "marin",
        pack: "500g",
        price: 849,
        imageUrl: "/images/marin_prawns.png",
        rating: 4.8,
        description: "Vibrant tiger prawns with firm, sweet meat.",
        stock: 45,
        isAvailable: true
    },
    {
        id: 'marin_seer',
        name: "Seer Fish (Surmai) Steaks",
        category: "marin",
        categoryId: "marin",
        pack: "1 kg",
        price: 949,
        imageUrl: "/images/marin_seer.png",
        rating: 4.7,
        description: "Thick, fleshy seer fish steaks, the king of fish.",
        stock: 0,
        isAvailable: true
    },
    {
        id: 'marin_mackerel',
        name: "Deep Sea Mackerel",
        category: "marin",
        categoryId: "marin",
        pack: "1 kg",
        price: 349,
        imageUrl: "/images/product_marin_mackerel.png",
        rating: 4.5,
        description: "Omega-rich whole mackerel, fresh from the deep sea.",
        stock: 80,
        isAvailable: true
    },
    {
        id: 'marin_barracuda',
        name: "Sea Barracuda",
        category: "marin",
        categoryId: "marin",
        pack: "1 kg",
        price: 499,
        imageUrl: "/images/marin_barracuda.png",
        rating: 4.4,
        description: "Wild-caught barracuda with a distinct flavor.",
        stock: 25,
        isAvailable: true
    },
    {
        id: 'marin_squid',
        name: "Calamares Squid Rings",
        category: "marin",
        categoryId: "marin",
        pack: "500g",
        price: 399,
        imageUrl: "/images/marin_squid.png",
        rating: 4.6,
        description: "Tender squid rings, perfect for frying.",
        stock: 50,
        isAvailable: true
    },
    {
        id: 'marin_pomfret',
        name: "Silver Pomfret",
        category: "marin",
        categoryId: "marin",
        pack: "1 kg",
        price: 1299,
        imageUrl: "/images/aqua_fish.png",
        rating: 4.9,
        description: "Ultra-premium silver pomfret with delicate texture.",
        stock: 20,
        isAvailable: true
    },
    {
        id: 'marin_tuna',
        name: "Bluefin Tuna",
        category: "marin",
        categoryId: "marin",
        pack: "1 kg",
        price: 1499,
        imageUrl: "/images/bluefin_tuna.png",
        rating: 5.0,
        description: "Sashimi-grade bluefin tuna loin.",
        stock: 10,
        isAvailable: true
    },
    {
        id: 'marin_sardine',
        name: "Fresh Sea Sardines",
        category: "marin",
        categoryId: "marin",
        pack: "500g",
        price: 199,
        imageUrl: "/images/marin_sardine.png",
        rating: 4.3,
        description: "Nutrient-dense sardines, daily fresh catch.",
        stock: 100,
        isAvailable: true
    },
    {
        id: 'marin_salmon',
        name: "Atlantic Salmon",
        category: "marin",
        categoryId: "marin",
        pack: "1 kg",
        price: 2499,
        imageUrl: "/images/atlantic_salmon.png",
        rating: 5.0,
        description: "Imported fresh Atlantic salmon fillets.",
        stock: 12,
        isAvailable: true
    },
    {
        id: 'marin_crab',
        name: "Blue Swimmer Crab",
        category: "marin",
        categoryId: "marin",
        pack: "1 kg",
        price: 899,
        imageUrl: "/images/marin_crab.png",
        rating: 4.7,
        description: "Sweet and meaty blue swimmer crabs.",
        stock: 18,
        isAvailable: true
    },
    {
        id: 'marin_snapper',
        name: "Red Snapper",
        category: "marin",
        categoryId: "marin",
        pack: "1 kg",
        price: 749,
        imageUrl: "/images/red_snapper.png",
        rating: 4.8,
        description: "Vibrant red snapper with white, flaky meat.",
        stock: 35,
        isAvailable: true
    },

    // --- AQUA CATEGORY ---
    {
        id: 'aqua_katla',
        name: "River Katla (Large)",
        category: "aqua",
        categoryId: "aqua",
        pack: "1 kg",
        price: 399,
        imageUrl: "/images/bengali_fish.png",
        rating: 4.6,
        description: "Pristine river Katla, thick and fleshy.",
        stock: 60,
        isAvailable: true
    },
    {
        id: 'aqua_rohu',
        name: "Freshwater Rohu",
        category: "aqua",
        categoryId: "aqua",
        pack: "1 kg",
        price: 299,
        imageUrl: "/images/product_bengali_rohu.png",
        rating: 4.7,
        description: "Standard rohu, fresh catch from local ponds.",
        stock: 120,
        isAvailable: true
    },
    {
        id: 'aqua_tilapia',
        name: "Premium Tilapia",
        category: "aqua",
        categoryId: "aqua",
        pack: "1 kg",
        price: 249,
        imageUrl: "/images/aqua_tilapia.png",
        rating: 4.4,
        description: "Farm-raised tilapia, mild and versatile.",
        stock: 90,
        isAvailable: true
    },
    {
        id: 'aqua_pangus',
        name: "Pangus Basa Fillet",
        category: "aqua",
        categoryId: "aqua",
        pack: "1 kg",
        price: 329,
        imageUrl: "/images/aqua_pangus.png",
        rating: 4.5,
        description: "Export-quality pangus fillet, fat-less.",
        stock: 75,
        isAvailable: true
    },
    {
        id: 'aqua_mirgal',
        name: "Fresh Mirgal Fish",
        category: "aqua",
        categoryId: "aqua",
        pack: "1 kg",
        price: 269,
        imageUrl: "/images/aqua_mirgal.png",
        rating: 4.2,
        description: "Traditional freshwater fish for home cooking.",
        stock: 0,
        isAvailable: true
    },
    {
        id: 'aqua_glass_carp',
        name: "Glass Carp Fish",
        category: "aqua",
        categoryId: "aqua",
        pack: "1 kg",
        price: 319,
        imageUrl: "/images/aqua_glass_carp.png",
        rating: 4.3,
        description: "Sleek glass carp with tender meat.",
        stock: 40,
        isAvailable: true
    },
    {
        id: 'aqua_silver_carp',
        name: "Silver Carp Fish",
        category: "aqua",
        categoryId: "aqua",
        pack: "1 kg",
        price: 229,
        imageUrl: "/images/aqua_silver_carp.png",
        rating: 4.1,
        description: "Economical silver carp, fresh daily.",
        stock: 85,
        isAvailable: true
    },
    {
        id: 'aqua_ropchand',
        name: "Fresh Ropchand",
        category: "aqua",
        categoryId: "aqua",
        pack: "1 kg",
        price: 449,
        imageUrl: "/images/aqua_ropchand.png",
        rating: 4.5,
        description: "The pomfret of freshwater, rich in taste.",
        stock: 30,
        isAvailable: true
    },

    // --- BENGALI CATEGORY ---
    {
        id: 'bengali_hilsa',
        name: "Padma Ilish (Hilsa)",
        category: "bengali",
        categoryId: "bengali",
        pack: "1 kg",
        price: 1899,
        imageUrl: "/images/bengali_hilsa.png",
        rating: 5.0,
        description: "Authentic Padma Ilish, the ultimate Bengali delicacy.",
        stock: 10,
        isAvailable: true
    },
    {
        id: 'bengali_aar',
        name: "Aar Mach Slices",
        category: "bengali",
        categoryId: "bengali",
        pack: "500g",
        price: 599,
        imageUrl: "/images/bengali_aar.png",
        rating: 4.7,
        description: "Boneless and fleshy river fish slices.",
        stock: 25,
        isAvailable: true
    },
    {
        id: 'bengali_koi',
        name: "Desi Koi Mach",
        category: "bengali",
        categoryId: "bengali",
        pack: "500g",
        price: 449,
        imageUrl: "/images/bengali_koi.png",
        rating: 4.6,
        description: "Climbing perch, a healthy traditional favorite.",
        stock: 40,
        isAvailable: true
    },
    {
        id: 'bengali_singi',
        name: "Fresh Singi Mach",
        category: "bengali",
        categoryId: "bengali",
        pack: "250g",
        price: 349,
        imageUrl: "/images/bengali_singi.png",
        rating: 4.8,
        description: "Catfish known for medicinal properties.",
        stock: 30,
        isAvailable: true
    },
    {
        id: 'bengali_bata',
        name: "Small Bata Fish",
        category: "bengali",
        categoryId: "bengali",
        pack: "500g",
        price: 249,
        imageUrl: "/images/bengali_bata.png",
        rating: 4.4,
        description: "Traditional small fish for Bengali curries.",
        stock: 70,
        isAvailable: true
    },
    {
        id: 'bengali_boal',
        name: "Valai boal (Slices)",
        category: "bengali",
        categoryId: "bengali",
        pack: "500g",
        price: 499,
        imageUrl: "/images/bengali_boal.png",
        rating: 4.5,
        description: "Silverside catfish slices, rich in flavor.",
        stock: 20,
        isAvailable: true
    },
    {
        id: 'bengali_putti',
        name: "Desi Putti Mach",
        category: "bengali",
        categoryId: "bengali",
        pack: "250g",
        price: 149,
        imageUrl: "/images/bengali_putti.png",
        rating: 4.3,
        description: "Tiny delicacies, perfect for crispy fry.",
        stock: 100,
        isAvailable: true
    },
    {
        id: 'bengali_maral',
        name: "Maral/Gajal Mach",
        category: "bengali",
        categoryId: "bengali",
        pack: "1 kg",
        price: 899,
        imageUrl: "/images/bengali_maral.png",
        rating: 4.7,
        description: "Snakehead fish, a rare Bengali treat.",
        stock: 15,
        isAvailable: true
    },

    // --- MASALA CATEGORY ---
    {
        id: 'masala_fish_curry',
        name: "Premium Fish Curry Masala",
        category: "masala",
        categoryId: "masala",
        pack: "100g",
        price: 49,
        imageUrl: "/images/masala_fish.png",
        rating: 4.8,
        description: "A signature blend of hand-pounded spices crafted specifically to enhance the natural flavors of river and sea fish curries.",
        stock: 200,
        isAvailable: true
    },
    {
        id: 'masala_turmeric',
        name: "Pure Haldi (Turmeric)",
        category: "masala",
        categoryId: "masala",
        pack: "200g",
        price: 75,
        imageUrl: "/images/masala_turmeric.png",
        rating: 4.9,
        description: "Farm-fresh, high-curcumin turmeric powder. Essential for fish marination to ensure hygiene and a vibrant golden hue.",
        stock: 150,
        isAvailable: true
    },
    {
        id: 'masala_mustard_powder',
        name: "Mustard Powder (Shorshe)",
        category: "masala",
        categoryId: "masala",
        pack: "100g",
        price: 85,
        imageUrl: "/images/masala_mustard.png",
        rating: 4.7,
        description: "Finely ground yellow and black mustard seeds. Perfect for classic Bengali dishes like Shorshe Ilish and Steamed Bhetki.",
        stock: 120,
        isAvailable: true
    },
    {
        id: 'masala_ginger_garlic',
        name: "Fresh Ginger Garlic Paste",
        category: "masala",
        categoryId: "masala",
        pack: "200g",
        price: 65,
        imageUrl: "/images/masala_gg_paste.png",
        rating: 4.6,
        description: "Authentic, preservatives-free ginger and garlic paste to remove raw odors and add a robust aroma to your seafood preparation.",
        stock: 180,
        isAvailable: true
    },
    {
        id: 'masala_panch_phoron',
        name: "Bengali Five Spice (Panch Phorone)",
        category: "masala",
        categoryId: "masala",
        pack: "100g",
        price: 45,
        imageUrl: "/images/masala_panch.png",
        rating: 4.8,
        description: "Traditional blend of Cumin, Nigella, Fenugreek, Fennel, and Mustard seeds. The secret to an authentic Bengali fish temper.",
        stock: 90,
        isAvailable: true
    }
];
